# =============================================================
# group_vars/windows_hosts.yml — AUTO-GENERATED by Terraform
# Template : terraform/templates/group_vars_windows.yml.tpl
# DO NOT EDIT manually — changes will be overwritten by CI/CD
# =============================================================

---
# ── WinRM connection settings ─────────────────────────────────
ansible_user: "${windows_user}"
ansible_password: "${winrm_password}"
ansible_connection: winrm
ansible_winrm_scheme: "${winrm_scheme}"
ansible_winrm_transport: "${winrm_transport}"
ansible_winrm_server_cert_validation: ignore
ansible_winrm_operation_timeout_sec: 120
ansible_winrm_read_timeout_sec: 150
ansible_port: 5985

# ── Windows shell settings ────────────────────────────────────
ansible_shell_type: powershell
ansible_shell_executable: None
