# =============================================================
# group_vars/all.yml — AUTO-GENERATED by Terraform
# Template : terraform/templates/group_vars_all.yml.tpl
# DO NOT EDIT manually — changes will be overwritten by CI/CD
# =============================================================

---
# ── Project metadata ─────────────────────────────────────────
project_name: "${project_name}"
environment: "${environment}"

# ── Timezone configuration (dynamic via CI/CD variables) ─────
# First timezone to apply (IANA format)
timezone_first: "${timezone_first}"

# Second timezone to apply (IANA format)
timezone_second: "${timezone_second}"

# Windows-specific timezone IDs (mapped from IANA in Terraform)
tz_first_windows: "${tz_first_windows}"
tz_second_windows: "${tz_second_windows}"

# ── Default connection users ──────────────────────────────────
default_user_linux: "${ansible_user_linux}"
default_user_windows: "${ansible_user_windows}"

# ── Ansible global settings ───────────────────────────────────
ansible_become: true
ansible_become_method: sudo

# ── Retry & timeout settings ──────────────────────────────────
connection_timeout: 30
command_timeout: 60
